import { Roster } from './app.data-types';

export const ROSTER: Roster[]= [
    {name:'Kyle George', position:'6', pictureURL:"", dateJoined:"", quote:""},
    {name:'Doug Kettlehut', position:'1', pictureURL:"", dateJoined:"", quote:""},
    {name:'Kyle Kubiak', position:'3', pictureURL:"", dateJoined:"", quote:""},
    {name:'Joe Katuzienski', position:'12', pictureURL:"", dateJoined:"06/2017", quote:"Ruck me? Ruck you!"},
    {name:'Ed Reyes', position:'4', pictureURL:"", dateJoined:"", quote:""},
    {name:'Pete Gjukis', position:'2', pictureURL:"", dateJoined:"", quote:""},
    {name:'Adrian Sharkey', position:'5', pictureURL:"assets/Adrian Sharkey.JPEG", dateJoined:"08/2010", quote:"Soccer is a gentlemen's sport played by hooligans. Rugby is a hooligan's sport played by gentlemen."},
    {name:'Joe Tidd', position:'6', pictureURL:"", dateJoined:"", quote:""},
    {name:'Brennan Diltz', position:'13', pictureURL:"", dateJoined:"", quote:""},
    {name:'Justin Biggs', position:'8', pictureURL:"", dateJoined:"", quote:""},
    {name:'Mike Voll', position:'11', pictureURL:"assets/Mike Voll.JPG", dateJoined:"08/2017", quote:"Amateur Rugger, Professional Drinker"},
    {name:'Adam Jolly', position:'15', pictureURL:"", dateJoined:"", quote:""},
    {name:'John Edwards', position:'14', pictureURL:"", dateJoined:"", quote:""},
    {name:'Ben Eich', position:'5', pictureURL:"", dateJoined:"", quote:""},
    {name:'Drunk Rick', position:'12', pictureURL:"", dateJoined:"", quote:""},
    {name:'Jake Farber', position:'7', pictureURL:"", dateJoined:"", quote:""},
    {name:'Derrick Yeoman', position:'10', pictureURL:"", dateJoined:"", quote:""},
    {name:'Westley Smith Jr.', position:'13', pictureURL:"", dateJoined:"", quote:""},
    {name:'Will Mishler', position:'3', pictureURL:"", dateJoined:"01/1416", quote:"Played everywhere and everyone"},
    {name:'Brandon Stahl', position:'7', pictureURL:"assets\Brandonstahl Stahl.jpg", dateJoined:"06/2014", quote:"I love being physical I love how the game of Rugby's continuous I just love all around rugby best sport ever played"},
    {name:'Shibli Moosa', position:'14', pictureURL:"", dateJoined:"01/1416", quote:"Go Springboks!"},
    {name:'Lee Kling', position:'1', pictureURL:"", dateJoined:"07/1996", quote:"I once was good"},
    {name:'Jason Pawlicki', position:'1', pictureURL:"assets/Jackson Pawlicki.JPG", dateJoined:"07/1996", quote:"I always wanted to be a back and kick the ball. I'm glad I was too fat for that. #ForwardLife "},
    {name:'Alexander Dorrier', position:'10', pictureURL:"assets/Alex Dorrier", dateJoined:"08/2017", quote:"Penn HS, Davenport University, Moose Rugby, Indiana University, Chicago Lions Rugby Club"},
]