import { Roster } from './app.data-types';

export const ROSTER: Roster[]= [
    {name:'Kyle George', position:'6', pictureURL:"", dateJoined:"", quote:""},
    {name:'Doug Kettlehut', position:'1', pictureURL:"", dateJoined:"", quote:""},
    {name:'Kyle Kubiak', position:'3', pictureURL:"", dateJoined:"", quote:""},
    {name:'Joe Katuzienski', position:'12', pictureURL:"", dateJoined:"06/2017", quote:""},
    {name:'Ed Reyes', position:'4', pictureURL:"", dateJoined:"", quote:""},
    {name:'Pete Gjukis', position:'2', pictureURL:"", dateJoined:"", quote:""},
    {name:'Adrian Sharkey', position:'5', pictureURL:"", dateJoined:"", quote:""},
    {name:'Joe Tidd', position:'6', pictureURL:"", dateJoined:"", quote:""},
    {name:'Brennan Diltz', position:'13', pictureURL:"", dateJoined:"", quote:""},
    {name:'Justin Biggs', position:'8', pictureURL:"", dateJoined:"", quote:""},
    {name:'Mike Voll', position:'11', pictureURL:"", dateJoined:"08/2017", quote:"Amateur Rugger, Professional Drinker"},
    {name:'Adam Jolly', position:'15', pictureURL:"", dateJoined:"", quote:""},
    {name:'John Edwards', position:'14', pictureURL:"", dateJoined:"", quote:""},
    {name:'Ben Eich', position:'5', pictureURL:"", dateJoined:"", quote:""},
    {name:'Drunk Rick', position:'12', pictureURL:"", dateJoined:"", quote:""},
    {name:'Jake Farber', position:'7', pictureURL:"", dateJoined:"", quote:""},
    {name:'Derrick Yeoman', position:'10', pictureURL:"", dateJoined:"", quote:""},
    {name:'Westley Smith Jr.', position:'13', pictureURL:"", dateJoined:"", quote:""},
    {name:'Will Mishler', position:'Coach', pictureURL:"", dateJoined:"01/1416", quote:""},
    {name:'Brandon Stahl', position:'7', pictureURL:".\Brandonstahl Stahl.jpg", dateJoined:"06/2014", quote:"I love being physical I love how the game of Rugby's continuous I just love all around rugby best sport ever played"},
    {name:'Shibli Moosa', position:'14', pictureURL:"", dateJoined:"01/1416", quote:"Go Springboks!"},
]